solution to the 0x11-python-network_1
